### ISSUE TITLE
can I feed detection boxes every 5 frame?

### ISSUE THREAD

**Issue by lyuchuny3** [abewley/sort#18]
Hi, 
In you code, you feed detection boxes every frame, and use tracker.update(detections) to update the location and track_id. I have a question, can I feed detection boxes every 5 frame?

**Comment by abewley** [comment]
Have you tried just skipping every other frame?

You may have issues with initialisation since after the first detection there is no velocity information. The prior is a zero velocity and for the case of highly dynamic video this would be invalid. Given a large displacement over the initial 5 frames after the first detection, the next detections may not overlap with the prediction and you will continuously be initialising new tracks.
Best thing to do would be to feed in more detections or replace the prediction step with something that looks at the intermediate frames.
