### ISSUE TITLE
trackers = sort.update(detections) gives the same bb as the detections

### ISSUE THREAD

**Issue by SelaOr** [abewley/sort#19]
Maybe I am missing something, 
but calling update with an array of detections always give me the same bb as the detections.
therefore i dont track anything but stay in the same place.
btw - if i want to detect only once objects, than only to update through the tracker - shall i call update with [] empty list?

**Comment by abewley** [comment]
If you are providing new detections each time the tracker will fuse the new information and update the object states before returning a filtered bounding box. However, it sounds like you want to just give it one set of detections for the initial frame only. Unfortunately, this will not work because SORT is a tracking-by-detection method. In other words without new detections, there is no information being added to providing the same detections over and over will make the system assume stationary objects or feeding empty lists will indicate that the objects are lost.

The use case you describe is better suited for trackers which make used of appearance information, one such example could be [HART](https://github.com/akosiorek/hart).

**Comment by SelaOr** [comment]
thanks, yes I understand.
So this tracker is tracking objects when the detections are given? meaning the output is exact objects in different frames? like a1, b1, c1 = a2, b2, c2 [the numbers are the frame num and the letters are the objects]

I will look at HART like trackers. Thanks :)

**Comment by abewley** [comment]
Yes, SORT aims to match the detections across frames to form multiple object trajectories.
