### ISSUE TITLE
Tracker re-initialization

### ISSUE THREAD

**Issue by Pirazh** [abewley/sort#26]
Hi, I am trying the Sort for tracking objects in multiple videos, but I noticed that when I re-initialize the tracker for the next video, mot_tracker=Sort(), the tracker ID do not reset and keeps increasing, I tried removing the tracker after each video but that does not help, do you know why is this happening?

**Comment by thevennamaneni** [comment]
Hi, In line 79, the author sets the `count = 0` and increments it in line 98 every time a new object is found `KalmanBoxTracker.count += 1`. But its never reset again. Maybe this is causing the count to just increment into the next video.

**Comment by abewley** [comment]
Yes that is correct.
Since the only requirement for a track ID is that it is unique I haven't changed it as this allows for combining multiple identities (for other learning tasks) across multiple videos.
Albeit, the name of the variable could be changed to better reflect it's purpose. 

@Pirazh do you have a particular use-case where you strictly need to reset the track ID?

**Comment by Pirazh** [comment]
Hi, Thanks for the response, that is true, I figured it out and forgot to mention it here, I reset the count parameter to zero after processing each video. I needed since I was processing different videos. 

Thanks again.

**Comment by williamgrimes** [comment]
I had a similar issue and added the following method to the `Sort` class, to be called after processing a video e.g. `mot_tracker.reset_count()`
```
  def reset_count(self):
      KalmanBoxTracker.count = 0
```
