### ISSUE TITLE
parameters of Kalman filter

### ISSUE THREAD

**Issue by landiaokafeiyan** [abewley/sort#42]
Hi, 
how do you set the parameters of Kalman filter? is it depends on the data or we can use the parameters as you set? 

The tracking bboxs are not exactly the location of the object,some lag exists, I suppose it's the problem of Kalman Filter parameters? Am i right?

**Comment by abewley** [comment]
The parameters were selected from a few samples on a subset of the MOT 2015 training dataset. 
The problem you are experiencing is due to the initial detection not knowing the velocity of the object so it will lag if the object is moving at the point of the first detection. You can try increasing the uncertainty (line 90) or work out a way to measure velocity (i.e. optical flow) with each detection.

**Comment by landiaokafeiyan** [comment]
Thanks Abewley !  
Actually I found the lag mainly because the RGB image is late then the depth image. but the parameters also contribute to the results.
Is that means we need to compute the velocity for every objects?because they may have different velocities(for example pedestrian  and car), that will need heavy computational. 
for that case what we can do to set the parameters?

**Comment by abewley** [comment]
Not sure where you are getting the "depth image" from but it sounds like you are doing more than 2D image tracking. Yes, estimating the velocity for each object would require additional components not supplied in this repo.
