### ISSUE TITLE
Understanding the physics intuition of:  if kf.x[6] + kf.x[2] <=0. 

### ISSUE THREAD

**Issue by vinayak-gosale** [abewley/sort#43]
First off. Thank you so much for the library and the research paper. 

I had a simple doubt.

Why are we checking **if the measurement of scale (area covered by box) and the estimate of scale sum up to less than or equal to zero or not**? The relevant line of code.
(I modified the `self.kf.x[6] *= 0.0` to `self.kf.x[6] = 0.0`) 

![capture](https://user-images.githubusercontent.com/16813164/44527090-869d5b00-a703-11e8-95b0-eef1b76aedca.PNG)

(Please correct me if my understanding of the problem is wrong as well)

What is the physics intuition to understand this line of code? Why are we checking this?

Thank you so much.

**Comment by abewley** [comment]
That is the sum of the scale and the delta scale which (due to the simplification of the linear dynamics model) can result in a negative scale. Setting the delta velocity (x[6]) to zero prevents the box from getting smaller. Put another way, this will preserve the scale for that prediction step to avoid the case where assignments cannot be made due to zero area.

**Comment by DanielXu123** [comment]
Hi , abewley, thanks for the comment.

I'm still having a little curious of x[6]. Does x[6] represent to delta scale or delta velocity ?
self.kf.x[6] = 0 -> set delta velocity to zero or set delta velocity to zero. Or, is gets the same results after all.

And is there any detailed explanation of delta scale ? I'm not so sure about why we will get negative values.
