### ISSUE TITLE
can the output be modified to get velocity of each object also?

### ISSUE THREAD

**Issue by rajvishnu27** [abewley/sort#59]
is it possible to get the velocity value also in the output sort file

**Comment by gmontamat** [comment]
I'm working on this and will comment if I figure out how to do it. In the meanwhile, has anyone figured out how to do it?

**Comment by abewley** [comment]
You could edit line 151 to something like:
`return convert_x_to_bbox(self.kf.x), self.kf.x[4:6]`
Where self.kf.x at index 4 and 5 are the estimated x and y pixel velocity.

**Comment by gmontamat** [comment]
Thanks!

**Comment by www7890** [comment]
Thanks for answering! I still wonder what the unit is for kf.x[4:6]?
what is the meaning of kf.x[4] and kf.x[5]? Are those velocity of x axis pixel and velocity of y axis pixel?
If so, then there the values are very small like 0.154 or -1.35 (0.154 pixel?)

**Comment by gmontamat** [comment]
I would say those are the velocities in pixels per iteration [pix/it.] in the x and y directions. So, for example if kf.x[4] == 0.154 means that we expect to find the x position of the centroid in the next iteration (`i+1`) in x_centroid[i+1] = x_centroid[i] + 0.154
I'm not using a unit of time because that depends at which frequency is SORT updated.

**Comment by www7890** [comment]
I see! Thanks for answer!
