### ISSUE TITLE
unexpected keyword argument 'compute_log_likelihood'

### ISSUE THREAD

**Issue by GOBish** [abewley/sort#95]
I am trying to run sort.py on MOT16 and I get the following error:

Processing MOT16-02.
Traceback (most recent call last):
  File "sort.py", line 306, in <module>
    trackers = mot_tracker.update(dets)
  File "sort.py", line 243, in update
    trk = KalmanBoxTracker(dets[i,:])
  File "sort.py", line 102, in __init__
    self.kf = KalmanFilter(dim_x=7, dim_z=4, compute_log_likelihood=True)
TypeError: __init__() got an unexpected keyword argument 'compute_log_likelihood'

**Comment by abewley** [comment]
Looks like the version of filterpy you have installed doesn't use this keyword arg. 
Since this is removed in the newest version of filterpy I've removed this from sort and updated the requirements. You should be able to do a git pull and it should work. 
If this works for you feel free to close the issue.

**Comment by GOBish** [comment]
thanks.

**Comment by prabh27** [comment]
In the requirements.txt, I see filterpy==1.4.5, I still get this error with version 1.4.5, but this error is not there with version 1.4.1 Maybe you want to update the requirements.txt file?
